### ISSUE TITLE
Unable to generate on server

### ISSUE THREAD

**Issue by duolabmeng6** [surfaceyu/edge-tts-go#1]
![image](https://github.com/surfaceyu/edge-tts-go/assets/59047063/d4b0434b-f460-4c48-911b-fc8855b5ce65)

**Comment by Hy9n0t1c** [comment]
hey dude has you solved this problem already? I use this tts package on my linux server and it can't generate.

**Comment by duolabmeng6** [comment]
> hey dude has you solved this problem already? I use this tts package on my linux server and it can't generate.

https://github.com/duolabmeng6/goefun/blob/master/model/etts/etts.go
