### ISSUE TITLE
The generated file is 0 bytes

### ISSUE THREAD

**Issue by LixvYang** [surfaceyu/edge-tts-go#2]

**Comment by haimachl** [comment]
at edgeTTS/edgeTTS.go line 86:
file, err := os.OpenFile(args.WriteMedia, os.O_APPEND|os.O_CREATE|os.O_TRUNC, 0644)

modify as follow:
file, err := os.OpenFile(args.WriteMedia, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, os.ModePerm)

it's good for me, enjoy!

**Comment by loopade** [comment]
> at edgeTTS/edgeTTS.go line 86: file, err := os.OpenFile(args.WriteMedia, os.O_APPEND|os.O_CREATE|os.O_TRUNC, 0644)
> 
> modify as follow: file, err := os.OpenFile(args.WriteMedia, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, os.ModePerm)
> 
> it's good for me, enjoy!

It's helpful to add the `O_WRONLY` permission.

See in [my commit](https://github.com/baohuiming/edge-tts-go)
